package com.jime.stu.bean

/**
 * @author PC
 * @date 2020/06/08 18:36
 */

data class EventJson(
    val phone: String,
    val udid: String,
    val userId: String,
    val systemname: String,
    val url: String,
    val efrom: String,
    val etype: String,
    val title: String,
    val mode: String,
    val productId: String,
    val referer: String,
    val channel: String,
    val networktype: String,
    val systemversion: String,
    val productversion: String,
    val eventTime: String,
    val power: String,
    val gyo: String,
    val batterystatus: String,
    val batteryType: String,
    val refererUrl: String,
    val mac: String,
    val imei: String,
    val idfa: String,
    val androidid: String,
    val deviceBrand: String,
    val deviceModel: String,
    val applicationid: String
)
//phone: "",
//udid: "",
//userId: "",
//systemname: "",
//url: "",
//efrom: "",
//etype: "",
//title: "",
//mode: "",
//productId: 0,
//referer: "",
//channel: "",
//networktype: "",
//systemversion: "",
//productversion: "",
//eventTime: new Date().getTime(),
//power: "",
//gyo: "",
//batterystatus: "",
//batteryType: "",
//refererUrl: "",
//mac: "",
//imei: "",
//idfa: "",
//androidid: "",
//deviceBrand:"",
//deviceModel:"",
//applicationid:"",